### ISSUE TITLE
How to build a selector that accept parameters

### ISSUE THREAD

**Issue by miquik** [pengooseDev/pengoose-jotai#1]
Hi,
Thanks for your project, it seems very interesting. However I have a question. How can I have a "selector" atom that accept parameters?
This is not possible in jotai directly but maybe in your implementation "selectors" can return atoms or "function that return an atom"

**Comment by pengooseDev** [comment]
@miquik 
 Thanks for your interest. In the current structure, the `selectorAtom` does not accept parameters.
It seems feasible to use an object, Map or Set within an atom to achieve the functionality of acceptiong parameters and returing values. If you need to implement complex logic --such as inheritance--, it might also be possible to inject a class object useing the static factory method pattern into the selector. However, if you determine that the sclae is growing, it would be better to manage the factory with a primitiveAtom rather than drievedAtom.
 
  What do you think about this approach? :)

**Comment by miquik** [comment]
Hi, 
I solved doing something like this:
```
public selectors = {
   ...
   changes: atom(get => (type) => get(this.changesAtom).filter(item => item.op === type))
   ....
};
```

Don't know if it is the best way but it works!

Thanks for your help, I have another different question but I will open another issue
